name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t luisuf1980/wingo:latest .

      - name: Push Docker image
        run: |
          docker push luisuf1980/wingo:latest
